# .streamlit/config.toml

[theme]
# Couleur principale du thème néon (Bleu Électrique)
primaryColor = "#00FFFF"

# Couleur de fond foncée pour un look "hacker"
backgroundColor = "#0E1117" 

# Couleur des éléments secondaires (barres, bordures)
secondaryBackgroundColor = "#262A31"

# Couleur du texte
textColor = "#FAFAFA"

# Utiliser une police de style terminal
font = "monospace" 
